# AUTOGENERATED! DO NOT EDIT! File to edit: ../00_core.ipynb.

# %% auto 0
__all__ = ['hello_world']

# %% ../00_core.ipynb 3
def hello_world():
    "Print the string \"Hello World!\""
    print("Hello World!")

